// Generated by scripts/fit.ts from 4470 SMTP-probed domains,
// matched against classifier 1.0.0-rc.3; see model/report-1.0.0.md.
// Refit rather than editing it.
import type { DnsScoreModel } from './score';

export const models: Record<'dns-reachability' | 'dns-only', DnsScoreModel> = {
  'dns-reachability': {
    id: 'dns-reachability',
    version: '1.0.0',
    intercept: -3.50735,
    coefficients: {
      hasMx: 4.31163,
      hasA: -0.141008,
      hasAaaa: -0.195878,
      hasSpf: 0.606265,
      knownProvider: 3.66963,
    },
  },
  'dns-only': {
    id: 'dns-only',
    version: '1.0.0',
    intercept: -3.7078,
    coefficients: {
      hasMx: 4.66821,
      hasA: -0.232622,
      hasAaaa: 0.11184,
      hasSpf: 0.634,
      multipleMx: 0.749704,
    },
  },
};
